"""autogenerated by genpy from hermes_move_arm_action/MoveArmGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class MoveArmGoal(genpy.Message):
  _md5sum = "9be71fa024812ef5d0c6601899b7c421"
  _type = "hermes_move_arm_action/MoveArmGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Move a robot arm
#
# goal message = the request
int32 arm				# number of the arm to control (1=left, 2=right)
int32 LEFTARM=1
int32 RIGHTARM=2

geometry_msgs/PoseStamped goal_position		# the target position of the wrist of the robot arm


================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  # Pseudo-constants
  LEFTARM = 1
  RIGHTARM = 2

  __slots__ = ['arm','goal_position']
  _slot_types = ['int32','geometry_msgs/PoseStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arm,goal_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveArmGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.arm is None:
        self.arm = 0
      if self.goal_position is None:
        self.goal_position = geometry_msgs.msg.PoseStamped()
    else:
      self.arm = 0
      self.goal_position = geometry_msgs.msg.PoseStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_i3I.pack(_x.arm, _x.goal_position.header.seq, _x.goal_position.header.stamp.secs, _x.goal_position.header.stamp.nsecs))
      _x = self.goal_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.goal_position.pose.position.x, _x.goal_position.pose.position.y, _x.goal_position.pose.position.z, _x.goal_position.pose.orientation.x, _x.goal_position.pose.orientation.y, _x.goal_position.pose.orientation.z, _x.goal_position.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.goal_position is None:
        self.goal_position = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.arm, _x.goal_position.header.seq, _x.goal_position.header.stamp.secs, _x.goal_position.header.stamp.nsecs,) = _struct_i3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.goal_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.goal_position.pose.position.x, _x.goal_position.pose.position.y, _x.goal_position.pose.position.z, _x.goal_position.pose.orientation.x, _x.goal_position.pose.orientation.y, _x.goal_position.pose.orientation.z, _x.goal_position.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_i3I.pack(_x.arm, _x.goal_position.header.seq, _x.goal_position.header.stamp.secs, _x.goal_position.header.stamp.nsecs))
      _x = self.goal_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.goal_position.pose.position.x, _x.goal_position.pose.position.y, _x.goal_position.pose.position.z, _x.goal_position.pose.orientation.x, _x.goal_position.pose.orientation.y, _x.goal_position.pose.orientation.z, _x.goal_position.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.goal_position is None:
        self.goal_position = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.arm, _x.goal_position.header.seq, _x.goal_position.header.stamp.secs, _x.goal_position.header.stamp.nsecs,) = _struct_i3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.goal_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.goal_position.pose.position.x, _x.goal_position.pose.position.y, _x.goal_position.pose.position.z, _x.goal_position.pose.orientation.x, _x.goal_position.pose.orientation.y, _x.goal_position.pose.orientation.z, _x.goal_position.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i3I = struct.Struct("<i3I")
_struct_7d = struct.Struct("<7d")
