controller_list:
 - name: ""
   action_ns: traj_action_
   default: true
   type: "FollowJointTrajectory"
   joints:
     - r_joint1
     - r_joint2
     - r_joint3
     - r_joint4
     - r_joint5
     - r_joint6
     - r_joint7
     - l_joint1
     - l_joint2
     - l_joint3
     - l_joint4
     - l_joint5
     - l_joint6
     - l_joint7

